#!/usr/bin/env python3
"""
Reproduce all primary figures for "Finite Prevention Windows" (Science Advances v2).

This script executes model analysis and figure generation in sequence.

v2 corrections (2026-05-06):
  * Figure 1 reverted to the 4-panel VL sweep (PEP_parenteral.py) — replaces the
    2-panel route comparison (make_figure_1_v2.py) which had model-artifact step
    functions and t_crit-vs-curve visual disconnect. The v2 PDFs go with the
    cleaner v1 main figure.
  * Figure 2: U=U band fix landed in PEP_stochastic_perelson.py — single axvspan
    outside the per-distribution loop, no legend duplication, PARTNER2 callout
    pinned at fixed low-y, U=U entry first in legend.
  * Figure 4 (selected city comparison): Panel C x-axis extended 70→0 (Path A,
    no truncation).
  * Suptitle stripped from Figure 1 (PEP_parenteral.py) for Science Advances
    house style — title now lives in the caption, not on the rendered figure.

Output naming convention for the v2 submission package:
  Figure_1_VL_Compression_PEP_Parenteral.{png,pdf}
  Figure_2_Stochastic_Efficacy_VL_Uncertainty.{png}
  Figure_3_City_Stratified_PEP_Efficacy.{png}
  Figure_4_CityComparison_Focus.{png}

The 2-panel route comparison (make_figure_1_v2.py) is no longer called.
The t_crit=34.5/60.5h numerical claims survive in §S6 supplementary prose.
"""

import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# =============================================================================
# Project structure
# =============================================================================
PROJECT_ROOT = Path(__file__).resolve().parent
SRC_DIR = PROJECT_ROOT / 'SRC'
REVISION_DIR = PROJECT_ROOT / 'v2_revision'

# Timestamped run directory — every invocation gets its own snapshot
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
RUNS_DIR = REVISION_DIR / 'runs'
FIGURES_DIR = RUNS_DIR / f"run_{timestamp}"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)


# =============================================================================
# Helpers
# =============================================================================
def run_command(cmd, env_add=None, cwd=None):
    """Run a shell command, optionally extending PYTHONPATH."""
    print(f"\n>>> Running: {' '.join(str(c) for c in cmd)}")
    env = os.environ.copy()
    if env_add:
        env['PYTHONPATH'] = (
            env.get('PYTHONPATH', '')
            + (':' if env.get('PYTHONPATH') else '')
            + str(env_add)
        )
    result = subprocess.run(cmd, env=env, cwd=cwd)
    if result.returncode != 0:
        print(f"ERROR: {' '.join(str(c) for c in cmd)} exited {result.returncode}")
        sys.exit(result.returncode)


def move_if_exists(src: Path, dest: Path) -> bool:
    """Move src → dest if src exists. Return True on success."""
    if src.exists():
        dest.parent.mkdir(parents=True, exist_ok=True)
        src.replace(dest)
        print(f"  Moved {src.name} → {dest}")
        return True
    return False


def copy_csvs(src_dir: Path, dest_dir: Path, label: str = ""):
    """Copy all CSVs from src_dir to dest_dir."""
    if not src_dir.exists():
        return
    n = 0
    for csv_file in src_dir.glob('*.csv'):
        shutil.copy2(csv_file, dest_dir / csv_file.name)
        n += 1
    if n and label:
        print(f"  Copied {n} {label} CSV(s) → {dest_dir}")


# =============================================================================
# Pipeline
# =============================================================================
def main():
    print("=" * 80)
    print("V2 REPRODUCTION PIPELINE: PREVENTION THEOREM")
    print(f"Run timestamp: {timestamp}")
    print(f"Output directory: {FIGURES_DIR}")
    print("=" * 80)

    # -------------------------------------------------------------------------
    # Figure 1: Source Viral Load as Window Compressor (Parenteral PEP)
    # -------------------------------------------------------------------------
    # Generated by SRC/perelson/parenteral/PEP_parenteral.py via plot_vl_sweep().
    # The script writes pep_parenteral_vl_sweep.{png,pdf} to the working dir;
    # we run from PROJECT_ROOT so the outputs land there, then rename + move.
    print("\n--- Figure 1: VL Window Compression (4-panel) ---")

    fig1_script = SRC_DIR / 'perelson' / 'parenteral' / 'PEP_parenteral.py'
    if not fig1_script.exists():
        # Fallback: try the project-root copy used in earlier iterations
        fig1_script = PROJECT_ROOT / 'PEP_parenteral.py'
    run_command([sys.executable, str(fig1_script)],
                env_add=str(SRC_DIR), cwd=str(PROJECT_ROOT))

    # PEP_parenteral.py main() saves to ./pep_parenteral_vl_sweep.{png,pdf}
    for ext in ('png', 'pdf'):
        src = PROJECT_ROOT / f'pep_parenteral_vl_sweep.{ext}'
        dest = FIGURES_DIR / f'Figure_1_VL_Compression_PEP_Parenteral.{ext}'
        move_if_exists(src, dest)

    # -------------------------------------------------------------------------
    # Figure 2: Stochastic Efficacy Under Source VL Uncertainty
    # -------------------------------------------------------------------------
    # Generated by SRC/perelson/stochastic/PEP_stochastic_perelson.py.
    # v2 patch: Panel B U=U band correctly placed (single legend entry, PARTNER2
    # callout at fixed low-y, legend reordered with U=U first).
    print("\n--- Figure 2: Stochastic VL Uncertainty (4-panel) ---")

    fig2_script = SRC_DIR / 'perelson' / 'stochastic' / 'PEP_stochastic_perelson.py'
    if not fig2_script.exists():
        fig2_script = PROJECT_ROOT / 'PEP_stochastic_perelson.py'
    run_command([sys.executable, str(fig2_script)],
                env_add=str(SRC_DIR), cwd=str(PROJECT_ROOT))

    fig2_default = PROJECT_ROOT / 'pep_stochastic_vl_uncertainty.png'
    fig2_target = FIGURES_DIR / 'Figure_2_Stochastic_Efficacy_VL_Uncertainty.png'
    move_if_exists(fig2_default, fig2_target)

    # Capture stochastic CSV outputs
    stochastic_csv_dir = PROJECT_ROOT / 'pep_stochastic_results'
    copy_csvs(stochastic_csv_dir, FIGURES_DIR, label="stochastic")

    # -------------------------------------------------------------------------
    # Figures 3 & 4: City-Stratified Analysis
    # -------------------------------------------------------------------------
    # Generated by city_stratified_figures.py — produces both:
    #   Figure 3: 34-city stratified PEP efficacy (4-panel)
    #   Figure 4: Selected city comparison focus (3-panel; Hartford / SanJuan /
    #             Jackson / Phoenix / Denver / Milwaukee)
    # v2 patch: Figure 4 Panel C x-axis extended [70,102] → [0,100] (Path A).
    print("\n--- Figures 3 & 4: City-Stratified Analysis ---")

    fig34_script = REVISION_DIR / 'city_stratified_figures.py'
    if not fig34_script.exists():
        fig34_script = PROJECT_ROOT / 'city_stratified_figures.py'
    run_command([sys.executable, str(fig34_script)],
                env_add=str(SRC_DIR), cwd=str(PROJECT_ROOT))

    # The script may write to either results/city_analysis/ or directly to outputs/
    city_results_candidates = [
        PROJECT_ROOT / 'results' / 'city_analysis',
        Path('/mnt/user-data/outputs'),
        PROJECT_ROOT,
    ]

    rename_map = [
        ('Fig_CityStratified_PEP.png',     'Figure_3_City_Stratified_PEP_Efficacy.png'),
        ('Fig_CityComparison_Focus.png',   'Figure_4_CityComparison_Focus.png'),
        # Re-run handling: outputs may already carry the v2 names
        ('Figure_3_City_Stratified_PEP_Efficacy.png',
         'Figure_3_City_Stratified_PEP_Efficacy.png'),
        ('Figure_4_CityComparison_Focus.png',
         'Figure_4_CityComparison_Focus.png'),
    ]

    for candidate_dir in city_results_candidates:
        if not candidate_dir.exists():
            continue
        for src_name, dest_name in rename_map:
            move_if_exists(candidate_dir / src_name,
                           FIGURES_DIR / dest_name)
        copy_csvs(candidate_dir, FIGURES_DIR, label="city")

    # -------------------------------------------------------------------------
    # Done
    # -------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("REPRODUCTION COMPLETE")
    print(f"Figures available in: {FIGURES_DIR}")
    print("=" * 80)
    print("\nExpected output files:")
    expected = [
        'Figure_1_VL_Compression_PEP_Parenteral.png',
        'Figure_1_VL_Compression_PEP_Parenteral.pdf',
        'Figure_2_Stochastic_Efficacy_VL_Uncertainty.png',
        'Figure_3_City_Stratified_PEP_Efficacy.png',
        'Figure_4_CityComparison_Focus.png',
    ]
    for fname in expected:
        path = FIGURES_DIR / fname
        marker = "✓" if path.exists() else "✗ MISSING"
        print(f"  {marker}  {fname}")


if __name__ == "__main__":
    main()
